version: '2'
services:
    rest-api:
        build: ./rest-api
        container_name: "location-api-prototype"
        environment:
            NODE_ENV: development            
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - 5000:5000
        links:
            - mongo
        depends_on:
            - mongo
    mongo:
        image: mongo:latest
        restart: always
        environment:
           MONGO_INITDB_ROOT_USERNAME: root
           MONGO_INITDB_ROOT_PASSWORD: example

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
           ME_CONFIG_MONGODB_ADMINUSERNAME: root
           ME_CONFIG_MONGODB_ADMINPASSWORD: example